import { apiClient, withFallback } from '@/api/client'
import { scheduleStops, type ScheduledRoute, type RouteStop } from '@/lib/route-timing'
import type { RouteTheme } from '@/types/route-theme'

type StopTemplate = Omit<RouteStop, 'startTime'>

// Fixed per-theme itinerary templates (24 stops total) — ported verbatim from
// origin/hslee's lib/routes.ts. Even hslee's real backend has no real
// recommendation algorithm behind /api/routes/generate (template lookup
// only), so this stays the permanent mock fallback, not a Step15 placeholder.
// Deliberately not localized (stop name/address/description stay in English
// regardless of UI locale, matching hslee's own design) — only the wizard
// chrome and theme/detail labels are localized via messages/*.json.
const ROUTE_TEMPLATES: Record<RouteTheme, StopTemplate[]> = {
  kpop: [
    {
      id: 'hybe-yongsan',
      name: 'HYBE Yongsan Area',
      category: 'K-pop',
      address: 'Yongsan-gu, Seoul',
      crowdLevel: 'mid',
      lat: 37.5241,
      lng: 126.9635,
      stayMinutes: 70,
      description: 'Start with the agency district and nearby fan photo spots.',
      tags: ['agency', 'photo'],
    },
    {
      id: 'hongdae-photo',
      name: 'Hongdae Photo Booth Street',
      category: 'Photo',
      address: 'Hongdae, Seoul',
      crowdLevel: 'high',
      lat: 37.5563,
      lng: 126.9236,
      stayMinutes: 60,
      description: 'Take quick fan-style photo booth shots before the area gets busier.',
      tags: ['photo booth', 'youth'],
    },
    {
      id: 'myeongdong-kpop',
      name: 'Myeongdong K-pop Store Loop',
      category: 'Shopping',
      address: 'Myeongdong, Seoul',
      crowdLevel: 'high',
      lat: 37.5637,
      lng: 126.985,
      stayMinutes: 80,
      description: 'Browse albums, character goods, cosmetics, and snack stops in one compact loop.',
      tags: ['shopping', 'albums'],
    },
    {
      id: 'han-river-night',
      name: 'Banpo Hangang Park',
      category: 'Night view',
      address: 'Banpo-dong, Seoul',
      crowdLevel: 'mid',
      lat: 37.51,
      lng: 126.9955,
      stayMinutes: 70,
      description: 'Close with a relaxed river view that works well for recap photos.',
      tags: ['river', 'night'],
    },
  ],
  drama: [
    {
      id: 'gyeongbokgung',
      name: 'Gyeongbokgung Palace',
      category: 'Culture',
      address: 'Jongno-gu, Seoul',
      crowdLevel: 'high',
      lat: 37.5796,
      lng: 126.977,
      stayMinutes: 90,
      description: 'A classic opening stop for palace drama energy and hanbok photos.',
      tags: ['palace', 'history'],
    },
    {
      id: 'bukchon',
      name: 'Bukchon Hanok Village',
      category: 'Culture',
      address: 'Jongno-gu, Seoul',
      crowdLevel: 'mid',
      lat: 37.5826,
      lng: 126.983,
      stayMinutes: 60,
      description: 'Walk quiet hanok alleys and keep the pace gentle for photos.',
      tags: ['hanok', 'photo'],
    },
    {
      id: 'gwangjang',
      name: 'Gwangjang Market Food Alley',
      category: 'Food',
      address: 'Jongno-gu, Seoul',
      crowdLevel: 'high',
      lat: 37.5701,
      lng: 126.9996,
      stayMinutes: 70,
      description: 'Add a market episode with bindaetteok, gimbap, and street-food texture.',
      tags: ['market', 'food'],
    },
    {
      id: 'namsan',
      name: 'Namsan Seoul Tower',
      category: 'View',
      address: 'Yongsan-gu, Seoul',
      crowdLevel: 'mid',
      lat: 37.5512,
      lng: 126.9882,
      stayMinutes: 80,
      description: 'Finish with a skyline scene that feels made for a final episode shot.',
      tags: ['view', 'night'],
    },
  ],
  mood: [
    {
      id: 'seoul-forest',
      name: 'Seoul Forest',
      category: 'Nature',
      address: 'Seongdong-gu, Seoul',
      crowdLevel: 'low',
      lat: 37.5443,
      lng: 127.0374,
      stayMinutes: 70,
      description: 'Open with a slower park walk and quiet photo corners.',
      tags: ['park', 'healing'],
    },
    {
      id: 'seongsu-cafe',
      name: 'Seongsu Cafe Street',
      category: 'Cafe',
      address: 'Seongsu-dong, Seoul',
      crowdLevel: 'mid',
      lat: 37.5447,
      lng: 127.0564,
      stayMinutes: 90,
      description: 'Take a longer cafe stop for rest, charging, and street photos.',
      tags: ['cafe', 'design'],
    },
    {
      id: 'ddp',
      name: 'Dongdaemun Design Plaza',
      category: 'Design',
      address: 'Jung-gu, Seoul',
      crowdLevel: 'mid',
      lat: 37.5665,
      lng: 127.0092,
      stayMinutes: 60,
      description: 'Add a clean design contrast with easy indoor/outdoor switching.',
      tags: ['design', 'photo'],
    },
    {
      id: 'ikseon',
      name: 'Ikseon-dong Hanok Alley',
      category: 'Food',
      address: 'Jongno-gu, Seoul',
      crowdLevel: 'high',
      lat: 37.574,
      lng: 126.9897,
      stayMinutes: 80,
      description: 'End around small restaurants, desserts, and evening alley lights.',
      tags: ['food', 'hanok'],
    },
  ],
  foodie: [
    {
      id: 'gwangjang-foodie',
      name: 'Gwangjang Market Food Alley',
      category: 'Food',
      address: 'Jongno-gu, Seoul',
      crowdLevel: 'high',
      lat: 37.5701,
      lng: 126.9996,
      stayMinutes: 80,
      description: 'Start with iconic market bites and a busy, easy-to-read Seoul food scene.',
      tags: ['market', 'street food'],
    },
    {
      id: 'ikseon-dessert',
      name: 'Ikseon-dong Dessert Alley',
      category: 'Dessert',
      address: 'Jongno-gu, Seoul',
      crowdLevel: 'high',
      lat: 37.574,
      lng: 126.9897,
      stayMinutes: 70,
      description: 'Move into hanok cafes, desserts, and softer photo corners after the market.',
      tags: ['dessert', 'hanok'],
    },
    {
      id: 'seongsu-bakery',
      name: 'Seongsu Bakery Loop',
      category: 'Cafe',
      address: 'Seongsu-dong, Seoul',
      crowdLevel: 'mid',
      lat: 37.5447,
      lng: 127.0564,
      stayMinutes: 75,
      description: 'Add a modern bakery and cafe district with room to rest and recharge.',
      tags: ['bakery', 'cafe'],
    },
    {
      id: 'euljiro-night-food',
      name: 'Euljiro Night Food Street',
      category: 'Night food',
      address: 'Jung-gu, Seoul',
      crowdLevel: 'high',
      lat: 37.5661,
      lng: 126.9919,
      stayMinutes: 85,
      description: 'Finish with neon-lit dinner streets and a strong end-of-day atmosphere.',
      tags: ['night', 'local food'],
    },
  ],
  creator: [
    {
      id: 'seoul-forest-creator',
      name: 'Seoul Forest Photo Corners',
      category: 'Photo',
      address: 'Seongdong-gu, Seoul',
      crowdLevel: 'low',
      lat: 37.5443,
      lng: 127.0374,
      stayMinutes: 65,
      description: 'Open with greenery, wide frames, and lower-pressure shooting time.',
      tags: ['photo', 'park'],
    },
    {
      id: 'seongsu-creator',
      name: 'Seongsu Design Street',
      category: 'Design',
      address: 'Seongsu-dong, Seoul',
      crowdLevel: 'mid',
      lat: 37.5447,
      lng: 127.0564,
      stayMinutes: 85,
      description: 'Collect storefronts, pop-up textures, cafes, and design-led transitions.',
      tags: ['design', 'short-form'],
    },
    {
      id: 'ddp-creator',
      name: 'Dongdaemun Design Plaza',
      category: 'Architecture',
      address: 'Jung-gu, Seoul',
      crowdLevel: 'mid',
      lat: 37.5665,
      lng: 127.0092,
      stayMinutes: 70,
      description: 'Use clean curves and open plazas for architecture and outfit frames.',
      tags: ['architecture', 'fashion'],
    },
    {
      id: 'namsan-creator',
      name: 'Namsan Seoul Tower View',
      category: 'View',
      address: 'Yongsan-gu, Seoul',
      crowdLevel: 'mid',
      lat: 37.5512,
      lng: 126.9882,
      stayMinutes: 80,
      description: 'Close with skyline light and an easy final clip for the route recap.',
      tags: ['skyline', 'night'],
    },
  ],
  history: [
    {
      id: 'gyeongbokgung-history',
      name: 'Gyeongbokgung Palace',
      category: 'Culture',
      address: 'Jongno-gu, Seoul',
      crowdLevel: 'high',
      lat: 37.5796,
      lng: 126.977,
      stayMinutes: 95,
      description: 'Begin with the royal palace axis, gates, courtyards, and classic Seoul context.',
      tags: ['palace', 'heritage'],
    },
    {
      id: 'bukchon-history',
      name: 'Bukchon Hanok Village',
      category: 'Culture',
      address: 'Jongno-gu, Seoul',
      crowdLevel: 'mid',
      lat: 37.5826,
      lng: 126.983,
      stayMinutes: 70,
      description: 'Continue through hanok alleys with slower pacing and neighborhood etiquette.',
      tags: ['hanok', 'walk'],
    },
    {
      id: 'insadong-history',
      name: 'Insadong Culture Street',
      category: 'Craft',
      address: 'Jongno-gu, Seoul',
      crowdLevel: 'mid',
      lat: 37.5743,
      lng: 126.9853,
      stayMinutes: 65,
      description: 'Add galleries, crafts, tea, and souvenir stops without leaving the heritage district.',
      tags: ['craft', 'tea'],
    },
    {
      id: 'gwangjang-history',
      name: 'Gwangjang Market Heritage Meal',
      category: 'Food',
      address: 'Jongno-gu, Seoul',
      crowdLevel: 'high',
      lat: 37.5701,
      lng: 126.9996,
      stayMinutes: 75,
      description: 'Finish with a traditional market meal that keeps the route practical and memorable.',
      tags: ['market', 'classic food'],
    },
  ],
}

// `detail`/`locale` aren't used by the mock body (theme alone picks the
// template), but are threaded through to match the real /api/routes/generate
// contract — added now so the real call is constructible without a later
// signature change.
export async function fetchScheduledRoute(
  theme: RouteTheme,
  detail: string,
  startTime: string,
  locale: string,
): Promise<ScheduledRoute> {
  return withFallback(
    async () =>
      (
        await apiClient.post<ScheduledRoute>('/routes/generate', {
          theme,
          detail,
          start_time: startTime,
          locale,
        })
      ).data,
    () => scheduleStops(ROUTE_TEMPLATES[theme], startTime),
  )
}
