import type { CrowdLevel } from '@/types/place'
import type { RoutePlan } from '@/lib/route-timing'

// Same storage key as the hslee reference (`lib/routes.ts`) so Step 10's
// RoutePage can read this draft directly once it's built.
const STORAGE_KEY = 'k-vibe-current-route'
// Persists the Persona-generated RoutePlan so RoutePage can show the docent
// player only for routes that originated from the Persona feature.
const PERSONA_PLAN_KEY = 'k-vibe-persona-plan'

export interface RouteStop {
  id: string
  name: string
  category: string
  address: string
  lat: number
  lng: number
  crowdLevel?: CrowdLevel
  description?: string
  tags?: string[]
  stayMinutes?: number
  startTime?: string
  // ISO "YYYY-MM-DD" — only meaningful when isAnchor is true. Non-anchor stops
  // get their date/startTime computed at render time by lib/route-schedule.ts.
  date?: string
  isAnchor?: boolean
  // true when this stop was generated by the Persona feature — used to show
  // the Docent button only on Persona-originated stops.
  fromPersona?: boolean
}

export function readRouteDraft(): RouteStop[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    return raw ? (JSON.parse(raw) as RouteStop[]) : []
  } catch {
    return []
  }
}

export function addStopToRouteDraft(stop: RouteStop): RouteStop[] {
  const next = [...readRouteDraft().filter((s) => s.id !== stop.id), stop]
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next))
  return next
}

/**
 * Upserts multiple stops at once — used when a feature (e.g. Analyze, Persona)
 * generates several stops together. Merges into whatever's already in the
 * draft (e.g. from Map) rather than replacing it, so stops added from
 * different entry points can be combined into one route.
 */
export function addStopsToRouteDraft(stops: RouteStop[]): RouteStop[] {
  const incomingIds = new Set(stops.map((s) => s.id))
  const next = [...readRouteDraft().filter((s) => !incomingIds.has(s.id)), ...stops]
  localStorage.setItem(STORAGE_KEY, JSON.stringify(next))
  return next
}

/**
 * Replaces the whole draft with RoutePage's own edited order/schedule.
 * Unlike addStop(s)ToRouteDraft (which merge in stops from another feature),
 * this is the route editor saving the same stops it's already showing —
 * not a cross-feature merge, so a full overwrite is safe here.
 */
export function saveRouteDraft(stops: RouteStop[]): RouteStop[] {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(stops))
  return stops
}

export function savePersonaRoutePlan(plan: RoutePlan): void {
  localStorage.setItem(PERSONA_PLAN_KEY, JSON.stringify(plan))
}

export function readPersonaRoutePlan(): RoutePlan | null {
  try {
    const raw = localStorage.getItem(PERSONA_PLAN_KEY)
    return raw ? (JSON.parse(raw) as RoutePlan) : null
  } catch {
    return null
  }
}

export function clearPersonaRoutePlan(): void {
  localStorage.removeItem(PERSONA_PLAN_KEY)
}
